apiVersion: v1
kind: ConfigMap
metadata:
  name: my-postgres-db-configmap
data:
  DB_USERNAME: "myuser"
  DB_NAME: "mydatabase"
  DB_HOST: "postgresql-service.default.svc.cluster.local"
  DB_PORT: "5432"